### ISSUE TITLE
Admin Privileges? 

### ISSUE THREAD

**Issue by nille02** [riderkick/FMD#1]
Why does fdm need the admin privileges?

**Comment by riderkick** [comment]
You don't need admin privileges unless you install fmd in restricted area like program files. 
Because FMD essentially is portable app, you can see fmd config, favorites and works file located in the same area as the exe file. FMD can't write this file without admin privileges. Usually if app installed to restricted area, its config file will resides in %appdata%. But, since developer doesn't have interest to make setup version, just enjoy this portable version.

**Comment by nille02** [comment]
Thats not the problem. I use the Builds from https://www.mediafire.com/folder/3ccy2c7g36hp3/Fmd#5uoguv1a9cdkh that Cholif linked and exacted them direct on the desktop.

**Comment by riderkick** [comment]
That was the same file, I just re-upload it here. Admin needed for shutdown and hibernate. Also used to run external process like updater, I don't change any of original code which execute it with admin privileged (see fmdRunAsAdmin in uBasUnit.pas). If you feel insecure, just look at the source what its can do, eliminated what you want and compile it for yourself.

**Comment by riderkick** [comment]
I've been change execution level to asInvoker for recent release. It should not asking for admin privileges anymore.

**Comment by nille02** [comment]
Thanks a lot, now it worked.
