### ISSUE TITLE
Arab Manga Problem

### ISSUE THREAD

**Issue by mohamed-imrani** [riderkick/FMD#10]
Hello.
First of all, I would like to thank you for this helpful program
But sadly, people in Arabic countries that like to read manga in Arab don't find what they're seeking for anymore, therefore, I would like to ask you to fix both the Manga-ar website in the program and Manga.ae that has changed its domain to mangaat.com, this one especially is really good and has the best quality so we ask you to fix this bugs as near as possible so we could download Arab manga and enjoy this program, thanks.

Regards, Mohamed Imrani.

**Comment by riderkick** [comment]
Manga-ar is fixed.
There is no change on manga.ae. Their website still working fine, so does FMD.

**Comment by mohamed-imrani** [comment]
I download the last version and tried to download from Manga-ar but it doesn't work, because the link has changed in Manga-ar, for example, the old one (which is on the program) the link is like:
http://manga-ar.net/Naruto/
but the new version of the site has the link like:
http://manga-ar.net/manga/%D9%85%D8%A7%D9%86%D8%AC%D8%A7-%D9%8A%D8%A7%D8%A8%D8%A7%D9%86%D9%8A%D8%A9/naruto-2/
-----------
Manga.ae still works yes but that's the old domain, now the owner has moved on to a new domain which is http://www.mangaat.com/, check it yourself if you don't believe me, and it doesn't download from any of them, neither the old one or the new one, so I'd appreciate if you could fix these bugs.

**Comment by riderkick** [comment]
Like I said in the changelog you have to rebuild manga list from scratch.
Close FMD, delete MangaAr.dat, run FMD, if it prompt to download from server click "No", and click books icon in right side of manga list option > "Update this manga list".
It will take a while to build fresh manga list. You can increase max number of thread per task in connection setting to speed up update. Or you can skip getting manga info by checking "Don't load manga information" in update settings. But you can't filter manga list with author, artist etc without manga info.

FMD can work without mangalist. Just paste the url to url box in mangainfo tab and hit enter or click >. You can download or add to favorites from there.

That's mean there is no change with MangaAe. Because the website is working well. The owner didn't remove the old website that's mean it was two different working website, whether it's contains the same manga or not but it's two running website. What you're doing is request new site support. Changing/adding new site isn't as simple to changing domain. I have to analyst the website first, and find a way to automatic the download programmatically.

**Comment by mohamed-imrani** [comment]
Okay, I've tried this and it worked, finally so thanks for responding and I'm working right now with a friend on a brand new website for manga, I'll let you know when we finish so you can add it to the list, thanks again.
