### ISSUE TITLE
MangaHere and FMD Filter bug

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#1025]
Unable to download at all on Mangahere.  There is no files at all in the download folder it created.

Second problem is that the filter when I do a filter for Skip Beat I get repetitive repeats in the result.
![fmd skip beat search](https://user-images.githubusercontent.com/16074561/36397670-b373afe8-1591-11e8-8679-156068bda9ae.png)

**Comment by 0xh3LL0** [comment]
> Unable to download at all on Mangahere. There is no files at all in the download folder it created.

try update your database, most likely the manga is deleted from mangahere, 
happened to me before, want to download shokugeki no soma, it run but no files at all at download directory, when i open mangahere, it deleted because it localized in english
anyway, mangahere still work for me, i finished download netsuzou trap just now...

**Comment by molitar** [comment]
Ok I tried to update database but I still show 2.  Senmanga I did an update list and it took forever and finally finished but I still show 2 Skip Beat with the same chapter number for Senmanga.  Seems somehow duplicates are being created on some sites.

**Comment by Tmp341** [comment]
Mangahere blocks me normally, but i couldn't see chapters via vpn.
