### ISSUE TITLE
Fmd not responding

### ISSUE THREAD

**Issue by leoteesh** [riderkick/FMD#1068]
Hi, after the recent update, fmds keep crashing for me - saying not responding. before this happened if i clicked on any tabs e.g. downloads/manga info, it automatically comes back to the favorite tabs. can you please advise?
![image](https://user-images.githubusercontent.com/21075197/36715187-fdd378c4-1b8c-11e8-9b4e-f0d49ee62d15.png)

**Comment by Tmp341** [comment]
Maybe your config file corrupted? Write down your options to a paper or notepad, then delete everything except:
- data folder
- works\favorites.db, downloadedchapters.db, and if you want downloads.db files.
- lua folder
- config\luamodules.json, modules.json files.

Then reinstall. Your config file might be corrupted.

**Comment by riderkick** [comment]
What version are you? IIRC this behavior is similar to #1059. Which is causing by the startup timer keep firing the ontimer event due to the interval is too low and there is a problem with startup event. So it keep repeating doing the startup timer which is load options etc. So your issue is because it keep reload the options that set the active tab/your saved active tab when you close fmd previously. This issue should have been fixed with the latest release.

**Comment by leoteesh** [comment]
thanks - it works now - changed the version
