### ISSUE TITLE
[Site Request] Add These sites

### ISSUE THREAD

**Issue by Tmp341** [riderkick/FMD#1080]
Please add : 

- [x] http://hatigarmscans.eu/ (Scanlation)
- [x] https://madpanda.cf (H-Site | Exhentai style site or it's mirror)

**Comment by ewasion** [comment]
Hello, I am the madpanda.cf admin.
It's an exhentai mirror for plebs who don't have an account and can only access the limited e-hentai library.

It often gets IP banned by e-hentai because of the large amount of traffic it's generating.
Please do not add it, it would only make matters worse. Thanks.

**Comment by Tmp341** [comment]
That's what i thought. Closing it now by this request.
