### ISSUE TITLE
MangaDex list isn't getting updated

### ISSUE THREAD

**Issue by Lorgra93** [riderkick/FMD#1183]
Launching a manual list update on MangaDex doesn't do anything.
It doesn't go past the 20020 titles which are already in the starting archive.
As it is right now, there are currently 24933 manga on MangaDex.

**Comment by R-Jimenez** [comment]
Yeah, doesn't seem to be any actual refreshing going on. As another note, manually inputting the URL into the address bar gets you the metadata for the series, but no chapters.

**Comment by Tomoko23** [comment]
@R-Jimenez  that's weird. I can fetch chapters with manual input just fine.

**Comment by R-Jimenez** [comment]
I had forgotten the MangaDex has a module section. I updated through the settings there and fixed my issue, but I have also cycled through an IP release since I posted, so it's possible that was indeed an issue as well.

The loading of the manga list is still not working however. Manual URL is the only way to get a manga ID'd past 20k as stated in OP.

**Comment by kmvi** [comment]
oh sorry list update is really broken. i'll fix it.
