### ISSUE TITLE
MangaFox watermark removal feature

### ISSUE THREAD

**Issue by mfripper** [riderkick/FMD#125]
Could you add a MangaFox watermark removal feature to Free Manga Downloader? Feel free to use [mfripper](https://github.com/mfripper/mfripper) or draw inspiration from it.

**Comment by StormJumper** [comment]
I noticed that when I try to use MangaFox to download it show no series to download.

**Comment by riderkick** [comment]
I don't know if using template would be the right call.
I notice the size of watermarks mostly 90px. And they squeeze the text to fit this area. that would make it dynamic. usually they resize the image first so the watermark can fit properly. but there is some old series with unexpected watermark.

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/commit/011bba9868f9b75ca133f952b89d5741a1055f70
https://github.com/riderkick/FMD/commit/32722debd2c1e2bf43cf84b352b663edca1c6fea

**Comment by mfripper** [comment]
Does you MangaFox watermark removal feature convert the scans to PNG before it removes the watermark? I can't see any PNG conversion in the code? Converting the JPG scans to PNG before watermark removal is vital to ensure that the scans won't deteriorate in quality due to [JPG being a lossy image format](http://lbrandy.com/blog/2008/10/my-first-and-last-webcomic/).

**Comment by riderkick** [comment]
I don't need to convert anything because I'm doing everything in RAM. Image loaded as bitmap. I also thresholding the image to reduce the noise and sharpen the edge, since it's just simple text, black in white.
You lost some quality because you use external tools to cut and save the pieces to file. If you save to JPG here, there will be quality loss, due to compression technology in JPG while saving the file. Saving to PNG will make sure the fidelity of all pixel. It will be identical with original JPG file.

There might be quality loss when saving back the cropped image to file. but I'm sure it will be unnoticeable.

**Comment by mfripper** [comment]
>I also thresholding the image to reduce the noise and sharpen the edge
Are you saying that you have the software do automatic "touch ups" on every image?

>If you save to JPG here, there will be quality loss, due to compression technology in JPG while saving the file. Saving to PNG will make sure the fidelity of all pixel. It will be identical with original JPG file.
That's exactly what I'm saying

>It will be identical with original JPG file.
That's exactly what I want.

>It does not increase the quality, just increase in file size.
I never claimed that it would improve the quality, just keep the quality identical to the original watermarked scans.
