### ISSUE TITLE
full list not downloading on hitomi.la

### ISSUE THREAD

**Issue by Ruriko** [riderkick/FMD#145]
I'm trying to download the full list from hitomi.la but it won't get the full list. It gave error:
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.27.0
Product Version   : Win32 Debug
FPC Version       : 3.1.1
LCL Version       : 1.7
Target CPU_OS     : i386_Win32
Host Machine      : Windows 8.1 64-bit
Path              : C:\Users\Administrator\Downloads\fmd_0.9.8.1\fmd.exe
Proccess Id       : 3480
Thread Id         : 1432
Time              : 12/28/2015 21:41:48
Ignored Exception : EImagingError,ERegExpr
Sender Class      : TUpdateMangaManagerThread
Exception Class   : EThread
Message           : Thread creation error: Not enough storage is available to process this command.

Exception Address : $0045345F
  $00453687
  $005C934F TFMDTHREAD__CREATE, line 51 of F:/GitRepo/Freepascal/FMD/baseunits/uFMDThread.pas
  $0073EFA5 TUPDATEMANGATHREAD__CREATE, line 100 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $007407EB TUPDATEMANGAMANAGERTHREAD__GETINFO, line 466 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $00741445 TUPDATEMANGAMANAGERTHREAD__EXECUTE, line 604 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $00453365
  $0041211E
  $7737A534
  $77668F8B
  $77668F61

**Comment by riderkick** [comment]
It seems you hit the limit of memory usage.
How much thread did you run?

**Comment by Ruriko** [comment]
I haven't even added any series to the download list since I'm trying to get the manga list generated first. I'm using the default download settings.

**Comment by Ruriko** [comment]
I don't suppose you have the list downloaded on your server? since you got most of it for other sites. It's not like I'm going to update the list quite regularly but probably every few months

**Comment by riderkick** [comment]
hitomi.la really has long list, it will take a long time to build the manga list.
I can't update the manga list. for awhile for some reason.
I just check the source, it may due to the large list that stored in tstringlist while populate the directory. this list is so large that it may hit the limit  of 2GB of usable ram for 32bit app. This is the reason I migrate the data from memory data to database file. But not the list of link when getting the list(temporary list of name and link before getting manga info), because this data isn't complete, I don't store it in database file. I may need to store it to temporary database file later.

Back to your problem, because hitomi.la has so many page for manga directory, so it take so much time just to get the list of all manga. And it even hit the limit. My solution is to use advanced.ini to limit total page number.
Example:

`[UpdateListDirectoryPageNumber]`
`HitomiLa=500`

It will just load first 500 page from the last page in reverse. After it done. Increase the it to 1000, it will load the first 1000 page, but will stop at page 500, because we already load it before. and so on, until all page loaded.
After all finished, remove this config. Because this module has sorted list, it will only load the page you miss from the first page. But, again. this website often update their manga, so to keep the list fresh, you need to update very often. That's why I suggest to use drop box instead. I personally never really used manga list. I like to browse the website directly and add it to favorite or download if I find it interesting.

**Comment by Ruriko** [comment]
thanks the settings trick helped
