### ISSUE TITLE
Script Issue or Manga site issue?

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#150]
I noticed in 0.9.28.0 after doing a "Download all list from server at once" works fine but when you do the first part option "Update all list at once" on some manga site it takes forever or it freezes. I am now at MangaTown and it is slow going.

**Comment by StormJumper** [comment]
Update date to this I did leave it running 24/7 and it did finish but it took longer the usual to complete.

**Comment by riderkick** [comment]
"Update list" will build manga list from the website by scraping the page one by one or in batch, depending on your connection setting or certain setting in script (some website has connection limit).
If there is really large number of page to be loaded, sure it will take a long time.
Do you realize how long we used to be to build such manga list? It can take a several day or even weeks.
With domdomsoft manga downloader you may even get longer times, because they only use single thread, and they always build from scartch. But they always running it their server nonstop, so you can always get fresh prebuild manga list from their server. While we rarely update our manga list.

Actually you don't need manga list at all, just use mangainfo tab or dropbox to download/add to favorite. I like this way, because I have to visit their website and help their cause.
