### ISSUE TITLE
"Check for new Chapter" not working correctly

### ISSUE THREAD

**Issue by Gevierthaufen** [riderkick/FMD#156]
The problem I have is the following:
When I click on Check for new Chapter, it checks all my favorites really fast except for a few that are checked for a longer time but still fast (under two minutes for 150 titles, in my old version it took 10 or 20 minutes). When it shows me the new chapters afterwards, only a few manga updates a shown even though there are way more that got updated (because I compared my favourites to the new chapters on batoto and the up-to-date mangalist in FMD). Ckecking a single title works but when I use the search-for-all-button it doesn't. 
Additionally the results I get for the multiple search always differ from the previous one. Sometimes the program finds 7 manga with new chapters and when I cancel and search again I find maybe 5 results and  2 of those 5 haven't been listed before.

This started happening somewhere after the release of version 0.9.14.1 which wasn't much of a problem back then because I didn't need the newer versions but since the the batoto login only bullshit I am now forced to use the latest version which unfortunately don't work for me. 

I hope you can help me

**Comment by StormJumper** [comment]
I also noticed that lag your seeing as well, all I did was leave my computer on and let FMD run til it finished.

**Comment by riderkick** [comment]
It seems the different between each new chapter check due to some connection failed.
If its batoto, then there is known problem with batoto server that limit client connection by ip, try to lower the concurrent connection. Maybe 1 or 2. And try again. You can also increase retry time.
If you open batoto in your browser it would likely also counted as another connection(currently batoto force use to use ssl connection, hence the connectioon will be keep-alive). So try to close batoto in your browser. And yes batoto server is really slow recently, that's why fmd appear slower when checking batoto.

**Comment by Gevierthaufen** [comment]
It worked, thanks. I just reduced the number of downloaded tasks to one and instead of 4 manga with updates I got 44.
Strange that it always worked with the older version I used but not the newer ones, though.

**Comment by riderkick** [comment]
It used to work back then with 4 connection or even more. Idk, maybe they change something in their server. You should know ba toto always short of resource, maybe they did limit the connection. Even more after they decide to only permit registered user to read the manga.
