### ISSUE TITLE
Weird error (Runtime Error 103)

### ISSUE THREAD

**Issue by spamtaztik** [riderkick/FMD#1569]
So for some reason my FMD today keeps giving me this error:
![fmd](https://user-images.githubusercontent.com/25314447/50158526-ea790e80-0306-11e9-8841-c3dc997cdd02.jpg)

After clicking OK, FMD would close. Just like that.
Added FMD to my antivirus' exclusion list, still the same (before today FMD was not in the exclusion list but ran just fine).

Any idea why?

**Comment by spamtaztik** [comment]
Apparently it only happens if I try to download a file that's very big (like those manhwas that has only 1 VERY LONG file in a chapter). For example: the law of the yama chapter 10 from mangadex. FMD can download up to a file size of 17 MB just fine (chapter 12), but for some reason it chokes on chapter 10. One can only guess how big the file is. I tried it several times already and if always chokes on chapter 10. 

So is this a bug, or something? Sure, I can circumvent this by downloading from different sites, but the problem -is- there. Just thought I'd let you devs know.

**Comment by muto4013** [comment]
no problem here, dl'ed all 12 chapter "law of the yama" from mangadex without problem.
chapter 10 is 39,2MB, and came as png.  FMD ver 0.9.156.0, Modules are uptodate .

**Comment by spamtaztik** [comment]
Holy smokes, 39 megs. Anyway, it went weird on mine but it was ok on muto4013's. What's wrong with mine then, any ideas?

**Comment by muto4013** [comment]
difficult to answer because of "lacks of info" about your system and settings :)
error 103 means "file not open" so i looked into the source code.
the first entry shows it could have something to do with the png - jpg convert, please check if you have the convert activated (option/ safe to), if so please disable it and test again. (here it creates invalid files or crashes). Other problem could be the dl-folder, keep name short and ascii only.
third idea would be the antivirus, try to exclude fmd and dl-folder.
That's the ideas which quickly came to mind, there are still more.

**Comment by spamtaztik** [comment]
Huh, the png>jpg converter? I forgot that option exist until just now. Okey dokey, thank you so much.
