### ISSUE TITLE
Download issues?

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#161]
When I use FDM the auto saved files for both fmd_0.9.30.0.7z and the x64 versions look like this:
946ec30c-bd4c-11e5-99ef-b89ce81e218d.7z = fmd_0.9.30.0_Win64.7z
038a374c-bd4f-11e5-8ffc-df3de86423d6.7z = fmd_0.9.30.0.7z
In the past using FDM didn't do this so was there a server download script change that cause it to break the download save file name? But if you use the FireFox Browser download I get the right names?

**Comment by riderkick** [comment]
Do you mean the updater save it to another file name? 
It doesn't matter, it should be able work with any file name. In the source itself, if you look at it, it will determine the file name based on the url, it will look at the last string with possible extension, or if there is none the file name will become "new_version". And it will process with any file name.
What is the error message you got?

Yesterday when I'm trying to download using updater.exe it always fail at around 20-25%, so updater retry and fail again with "404 file not found", because the redirected url was temporary url. 
Today, there is no problem, updater successful to download in first try.
I'll improve this part to get back the previous url.

**Comment by riderkick** [comment]
Do you mean the updater save it to another file name? 
It doesn't matter, it should be able work with any file name. In the source itself, if you look at it, it will determine the file name based on the url, it will look at the last string with possible extension, or if there is none the file name will become "new_version". And it will process with any file name.
What is the error message you got?

Yesterday when I'm trying to download using updater.exe it always fail at around 20-25%, so updater retry and fail again with "404 file not found", because the redirected url was temporary url. 
Today, there is no problem, updater successful to download in first try.
I'll improve this part to get back the previous url.

**Comment by riderkick** [comment]
Do you mean the updater save it to another file name? 
It doesn't matter, it should be able work with any file name. In the source itself, if you look at it, it will determine the file name based on the url, it will look at the last string with possible extension, or if there is none the file name will become "new_version". And it will process with any file name.
What is the error message you got?

Yesterday when I'm trying to download using updater.exe it always fail at around 20-25%, so updater retry and fail again with "404 file not found", because the redirected url was temporary url. 
Today, there is no problem, updater successful to download in first try.
I'll improve this part to get back the previous url.

**Comment by StormJumper** [comment]
Yes it saved it with all the number name as shown instead of the second half that it should've been right file names. I try again and see how the new update saves with FDM and report if it does the same download or not.

**Comment by StormJumper** [comment]
Well if I copy the link itself and then use create download in FDM it will produce the right file name. But in the past I know by opening a new link to the file FDM was able to save the correct file name.

**Comment by riderkick** [comment]
I don't understand what you're trying to say. How do you create download in FMD?
You're talking about updates file or what?

**Comment by StormJumper** [comment]
Ok here's how it happens. Using Firefox with FDM plugin installed.
1. Click on update
2. select and hi-light : https://github.com/riderkick/FMD/releases/download/0.9.31.1/fmd_0.9.31.1.7z
3. Right click "open link in new tab"
4. FDM opens up and display file name : 02a3d872-c099-11e5-8cf4-02dece20177f.7z
5. If I cancel FDM then the Browser download windows pop and says: fmd_0.9.31.1.7z  giving the right file name.

In the past doing the same steps gave the correct file name not was shows in 4. The same problems shows on the x64 version.

**Comment by riderkick** [comment]
Oh. You are talking about FDM, not FMD. 
Well, it just a naming. So what is the problem? This is not related to FMD at all. It just how github handle their files. They use amazon s3. So, Its getting redirected and all.
Actually, there is url parameter `filename` in temporary url given by amazon s3. If FDM doesn't pick it, then its their fault. Report to them, not here.
