### ISSUE TITLE
[Request] Remove leading 0's on Chapter and files.

### ISSUE THREAD

**Issue by asthemic** [riderkick/FMD#167]
I've set the save to options to 1 for both volume and chapter, although it doesn't seem to be working, unless I've misunderstood the naming system:
`%MANGA% %NUMBERING%`
^ is what I've got set for Chapter Folder Name.

Currently using Powershell to clean up:
`$Path = 'E:\Manga\fmd_0.9.31.0_Win64\downloads'
Get-ChildItem $Path -Recurse | ?{ $_.PSIsContainer } | %{Get-ChildItem $_.FullName -Recurse} | ?{ $_.PSIsContainer } | %{$Newname = $_.Name -replace '(?<=\D)(0*)(?=.+)';If ($_.Name -ne $Newname){Rename-Item -path $_.FullName -newName $Newname};}
Get-ChildItem $Path -Recurse | ?{ ! $_.PSIsContainer } | %{$Newname = $_.Name -replace '(^0*)(?=.+)';If ($_.Name -ne $Newname){Rename-Item -path $_.FullName -newName $Newname};}`

**Comment by asthemic** [comment]
Also excellent work updating and improving this program. :)

**Comment by riderkick** [comment]
`%NUMBERING%` is auto numbering that you see in chapter list on manga info tab. It wasn't chapter number, but just auto number in case there is no chapter number or even no title, or so i thought. It's have been there since the original FMD by Akarink. I think it's quite useful for some case.

Just use `%CHAPTER%` is enough.
Regarding to altering chapter/volume numbering, it may not as effective you expect. As you see, there is a lot of varieties of how chapter/volume number constructed. Sometimes it just so random and hard to pick which one is. But in most case it's works fine.
