### ISSUE TITLE
Cannot Download from PsychoPlaay

### ISSUE THREAD

**Issue by LittleDaoist** [riderkick/FMD#1707]
Can't download mango from Psychoplay

**Comment by SDXC** [comment]
Seems to be CloudFlare that blocks FMD. Loading the chapter list doesn't seem to be a problem, but getting the image links fails because of CloudFlare. The CF workaround doesn't seem to work with PsychoPlay as the anti-cf procedures and functions probably weren't implemented for PsychoPlay yet. I'll try to look further into it. Alternatively I'll try to create a lua script instead.

Getting into the sourcecode is quite a bit of work to do. At least I get the project to compile properly.

**Comment by SDXC** [comment]
@LittleDaoist I was doing something wrong before. The Cloudflare workaround works. I put up a PsychoPlay specific workaround on my wiki:
https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-PsychoPlay

**Comment by SDXC** [comment]
@LittleDaoist Please close this ticket if everything is okay for you. It's easier for me to check the old tickets in riderkicks repo if the actually fixed/added/etc. issues are closed. A general Cloudflare bypass mechanism is planned.
