### ISSUE TITLE
Suspicious favorite links

### ISSUE THREAD

**Issue by 27136773** [riderkick/FMD#1717]
Hello,

i got a user that provided me with a favorite database from FMD which has some inconsistent links (see attached image).

Not sure if this behavior is intentional or a bug, so i just wanted to let you know about this...

----
![favorites](https://user-images.githubusercontent.com/27136773/55273173-2b9a9a80-52c8-11e9-9b60-049cec25c787.png)

**Comment by Tmp341** [comment]
There were a couple of times, when a website changes it's structure, and if you haven't deleted your ``data`` file or ``favorite`` entry , you would see double mangas in your lists. So, i guess it is a situation like that. I think it is an error, since FMD's latest activity was fixing ``connectivity/download`` error, not fixing ``double mangas``etc.

**Comment by SDXC** [comment]
@ronny1982 Hi my fellow Swiss man. Please close this ticket if everything is okay for you. It's easier for me to check the old tickets in riderkicks repo if the actually fixed/added/etc. issues are closed. Otherwise open an issue in my fork instead. On the other hand, fixing the existing db files isn't an option right now. But I will probably try to optimize the behavior in the favorites db.

**Comment by 27136773** [comment]
Developers of FMD are now aware of the behavior in favorites.db
The behavior has been adapted for import functionality in https://github.com/manga-download/hakuneko/commit/6789526a9d85d5817f565f132db654a1d896d7ba

Greetings from Graubunden :P
