### ISSUE TITLE
Can't download manga at all since newest version

### ISSUE THREAD

**Issue by mikazuki7** [riderkick/FMD#22]
Can someone help me? After updating to newest version, I couldn’t download manga at all.

https://i2.wp.com/puu.sh/hEIEF/b42adee838.png
https://i2.wp.com/puu.sh/hEIxa/7faa371159.jpg

but I can access Batoto site with no problem
http://puu.sh/hEIAD/760ee3ecb4.jpg

and I can check for new updates on my Favorites
http://puu.sh/hEITM/83036ed3d5.png

This is my configuration file
http://www.mediafire.com/download/1y1whpjgb4wdde1/fmd_0.9.9.rar

**Comment by rhoen91** [comment]
Can you open and read a chapter? The problem seems to be with Batoto, I just tried and while I can load the site, I can't read any of the manga.

**Comment by rsiller2** [comment]
Looks like they are changing the image servers on bato.to per this forum post
https://bato.to/forums/topic/22449-juggling-image-servers/#entry1559543

**Comment by riderkick** [comment]
like rsiller2 mentioned, it was due to changes on their server. they seems to be moving around their images. Some manga stored on different server. On your connection log. img.bato.to is failed to connect. That's can be mean img.bato.to is down.
Bato.to server seems overloaded. On my log, there is always "503 Server unavailable" from bato.to. Try to increase your max connection retry may help. On my case often there is about 1 out of 3 successful connection.
