### ISSUE TITLE
S2scanlations broken + some stuff.

### ISSUE THREAD

**Issue by MammothJerk** [riderkick/FMD#23]
old URL: http://s2scanlations.com/online/series/*/

new URL: http://reader.s2smanga.com/series/*/

I would like to be able to have the "View manga infos" option when right-clicking in the DOWNLOADS section. just for a bit of easier navigation if you need to download more chapters without having to search for the manga again to open the info.

When a chapter from a manga gets AUTOMATICALLY downloaded it is not marked as previously downloaded with the green line in the Manga Infos.

and just a minor, minor remark, the word "infos" is not grammatically correct, its just "info"

lastly the latest update to 0.9.9.3 doesnt seem to work from the intergrated updater
![](http://puu.sh/hHb2b/6810fdae88.png)
it did however work from just dragging the release fmd_0.9.9.3_Win64.7z files from the zip to the folder like usual. so not a big problem.

**Comment by riderkick** [comment]
I'll look at it.

Downloaded list from favorites isn't merged with the one from manual download. I don't know if it's the right thing to merge them. Because when you add some manga to favorite, for starting point it will mark all current found chapters as downloaded, even though you're not download anything. I may be able to store the new downloaded chapter from favorite to main downloaded list.

Yes the old translation still messed up, I'm planning to use gettext for internalization, for easier translation. I don't have time to complete it yet. I'm not natively speak English, so excuse my language. When I'm finish migrate it to gettext, then everyone can easily translate it using po editor.

I thought i put a notice on changelog. There is previous updater bug which fail to redirect to correct url.

**Comment by MammothJerk** [comment]
great

okay do what you can :D

as i said its just a very minor thing, honestly it doesnt really matter to me as long as everything works. =)

i mustve missed the changelog then, my bad

**Comment by riderkick** [comment]
I just look at downloaded chapter list. It's storing the index of list instead of url. so we can't merge it with the one from favorites.
I've to change it first. But that's mean old our downloaded chapter list will be loss. But, I think it's better to store url instead of the index. Because index isn't reliable. If chapter is inserted between, than this index isn't reliable anymore.
