### ISSUE TITLE
Failed to Download for some series on Batoto

### ISSUE THREAD

**Issue by aguswinger** [riderkick/FMD#262]
When I tried to download chapters from Batoto, download **failed** in this series
http://bato.to/comic/_/comics/kuragehime-r218
http://bato.to/comic/_/comics/silver-spoon-r496

but for this series can successfully download chapters
http://bato.to/comic/_/comics/kuro-r11140
http://bato.to/comic/_/comics/shokugeki-no-soma-r7530

**Comment by riderkick** [comment]
Checking the failed chapter with a browser. I got this:
![sshot-2016-05-29- 02-04-55](https://cloud.githubusercontent.com/assets/4972676/15628994/d45d37ac-2541-11e6-970d-f999b160c441.jpg)

**Comment by riderkick** [comment]
It seems this chapter can only be accessed by registered user.
The commit above should fixed the issue. But you have to make sure the account is working. There is no way to identify if account is working at this point when downloading image, because it's only load partial document. If download keep failed, try to refresh the the batoto account in Options>Accounts, and make sure its OK.

**Comment by aguswinger** [comment]
It works now thanks mate
