### ISSUE TITLE
Error while downloading manga lists 

### ISSUE THREAD

**Issue by VulkHead** [riderkick/FMD#3]
So this error appears every time I try to download a manga list from the server. It seems is downloading just fine, but when the download is done appears this error and the manga list won't load..    
![capture](https://cloud.githubusercontent.com/assets/11966520/7196004/72d6c200-e497-11e4-87f5-c4e1978962da.PNG)
I can get the manga list if I click in ''Update this manga list'' instead of download the manga list as usual but is stupidly slow, I don't know if is a bug or something but when I'm updating can last like 6 to 7 hours (a manga list of 18622) until is done..

PD: Thank you for fixing submanga

**Comment by riderkick** [comment]
Try download the latest version again. I replace  0.9.8.3 release with new files. You may download it before I replace the files. I senselessly delete the files because I thought no one download it yet.
This issue was fixed with this commit https://github.com/riderkick/FMD/commit/b22b53e868fe9da3186579a52b59d3ff7c644807

Btw, mangalist that you'e trying to download is not available in sf, so it can't be done automatically. You have to manually download the files from my mediafire folder and extract it to data\. (there should be a message box about this when you trying to update the list). I'm considering to relocated data files to another place with direct link allowed. Just yet to found the place.

Just for reminder, FMD can work without mangalist, you just have to put the url in url box in mangainfo tab and click go button or enter. You can download it from there or add it to favorites.
