### ISSUE TITLE
Some features

### ISSUE THREAD

**Issue by pedrotk** [riderkick/FMD#301]
some possibility to get this features?

- Auto update manga list        
update manga list every 6 hours
- Detailed download error   
can't figure why i get "Failed, try resuming this task!" some times
- Filter for each manga website     
like MangaFox and and MangaReader have different filters saved

**Comment by 7h3Cub3** [comment]
from experience the failed to download is often due to FMD unable to record the files on disk (often happens when you have very long chapters/folders names) but yeah i agree a little log tab would be great.

**Comment by riderkick** [comment]
Do people really still depend on manga list?
For instant fmd is just automated web scrapper, It doesn't integrated to any website. It just simply collect the data from webpages. Filter is just simply filtering the data that have been collected before, with basic functionality. Its can't be compared with "advanced search" provided by the website itself.
And there is 100+ website supported, basic feature means feature for all.
It will be easier if there is only 1 website supported so we can follow closely.
I personally prefer to not use manga list at all. Just use drag n drop function. It much easier.

"Failed, try resuming this task" means there is temporary connection issue or unexpected response from server(can be website have been changed). Just try to resume the task, you may also need to pay attention to your connection settings, some server is just slow to respond, so don't set the timeout to short, for example: 30s timeout and 5 retry times.

"Failed to create dir" means fmd can't access the directory, can be caused by permission issue or antivirus. Try to run as admin may fix the problem. In the past there is a bug with long path, I believe it's have been fixed. So the error must be something else.

Actually there is another status from the module other than just simply error. NO_INFORMATION, NETWORK_ERROR and such. But to return this status correctly we have to test for every status necessary. There is 100+ website, and we have to change all of that. I think that's not really necessary, because error usually just connection issue or website changed. Nothing more, except if there is bug in tdownloadmanager itself, but it should affect all website.
And there is more complication, fmd right now run on hybrid module, the module that come from older version of fmd which using include files directly to tdownloadmanager, and the new module that register itself at runtime via twebsitemodules. The state of the source itself is chaotic. It's hard to change because of how it's designed to begin with.

**Comment by 7h3Cub3** [comment]
I see, explained like this it make sense :)

**Comment by jras13** [comment]
sir, may i request some features added, if you willing of course :). like this one..

- Custom Color Options
a custom color for manga list that completed, already downloaded and removed from favourite.

maybe if you are interested, i suggest some features below...
Further Additional Option (Optional, can be turned on or off)

- re-check manga folder before downloading (only if download is begin from chapter 1) to avoid redudancy data.

- if already downloaded and or favourited from other site, i.e. mangahere, but download and favourite again from mangafox which is has same title, the favourite from mangahere will be removed and changed into mangafox.

- Give an alert if storage is full or the folder name is too long.

thanks for the attention
best regard

JrasDrasil13

**Comment by riderkick** [comment]
- Custom color would be nice. I've been planning to add custom color for downloads, favorites, and all possible list. But that will be time consuming, so I don't have time for it yet. Maybe later.
- Before download, fmd will check the destination folder, if it's already there it will be skipped. Note that if you have different filename it will be ignored. The same if you compress the folder to zip or cbz, it will be ignored too.
- It is best to leave the choice to user. Some user like to add same title from different website and store it in different location, e.g. for title with different languages.
- When trying to write file to disk, if disk full, it should throw an exception dialog. Path length is strictly coded, longer path will be stripped.

**Comment by jras13** [comment]
thanks for the reply sir, please be noticed i just suggested the feature, it's not like i order or demand you to do it or something like that sir.. :), 
and thanks for all your effort for always updating FMD features until these day and the explanation for my suggestion above, hoping forward to see the custom color will be available someday. and now my case is closed :) . 

thanks for the attention
best regard

JrasDrasil13
