### ISSUE TITLE
Favorites check stuck

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#305]
Favorites check stuck when checking kissmanga

**Comment by StormJumper** [comment]
I confirm this is also freezes when I do a kissmanga check on 0.9.68.0. The site opens fine so must be a script issue that is will need to be updated.

**Comment by StormJumper** [comment]
I also add ReadComicOnline is also freezing when doing a update check.

**Comment by riderkick** [comment]
It's working fine here.
![sshot-2016-06-22- 01-10-42](https://cloud.githubusercontent.com/assets/4972676/16239277/b05088fe-3816-11e6-8c55-3815faf1a9f6.jpg)

**Comment by jras13** [comment]
the site demand cookies so it only can accessed using browser. i've checked the site and its working. but from FMD can't access the path or updating the list. mine is using proxy, idk if it's because proxy or cookies.
![aaaa](https://cloud.githubusercontent.com/assets/20046326/16243281/b10c357c-3820-11e6-863e-063ff890fe14.PNG)

**Comment by riderkick** [comment]
It's working fine here
![sshot-2016-06-22- 04-20-38](https://cloud.githubusercontent.com/assets/4972676/16244890/ce50a1c6-3830-11e6-902c-0b4d30ebc11b.jpg)

**Comment by StormJumper** [comment]
ReadComicOnline is there but if you do a check for updates from FMD it freezes.

**Comment by Hexaf** [comment]
It didn't work. Like StromJumper if check update from kissmanga it freezes.
![kissmanga](https://cloud.githubusercontent.com/assets/16042929/16246815/16aaf8c2-3831-11e6-8971-0ce2b641c08f.PNG)

**Comment by riderkick** [comment]
How long it freeze?

**Comment by abhi98** [comment]
i waited for 5 min and then it works fine for kissmanga

**Comment by StormJumper** [comment]
So far with 0.9.69.0. Feeze updates.
EyeOnManga, KissManga, MangaStreamTo, ReadComicOnline.
If you do a "Update all lists at once" will freeze at each of these manga sites. I know because I uncheck each of these and redid the same process. The web site probably is fine but something on their site is intentional set to prevent such programs as FMD from working correctly. KissManga, for me has frozen far longer then 5 min I let it run before I went to work and came back and it had not moved. With those manga sites unchecked the update checks have no problems.

**Comment by Hexaf** [comment]
until now it still freeze

**Comment by riderkick** [comment]
They use cloudflare anti-ddos attack. There is many variant of it. But the common one is the "wait for 5 seconds". There is another with captcha that I can't bypass yet.
Maybe it's depend on regional. Try to use vpn or ssh tunnel from different country.

**Comment by 7h3Cub3** [comment]
i confirm, when checking kissmanga it's like before it'll get stuck on it until you used up all your connection and it'll also freeze FMD connection system making it unable to be closed properly.

**Comment by Vrosky** [comment]
Gets stuck on Kissmanga when checking on the latest version (0.9.69.0), works fine on 0.9.66.0.

**Comment by StormJumper** [comment]
@Vrosky, what if you did the same update for EyeOnManga, MangaStreamTo, ReadComicOnline  in 0.9.66.0?

**Comment by Vrosky** [comment]
Update works on ReadComicOnline but the download doesn't same goes for Kissmanga. Can't access the site for EyeOnManga & MangaStreamTo.

**Comment by Vrosky** [comment]
Downloading a clean copy of FMD and importing my favourites seemed to have worked. Kissmanga updates.

**Comment by StormJumper** [comment]
Tried that remove -1 and all the previous manga checked but didn't freeze. Not sure if they downloaded the update but no more freeze.

**Comment by 7h3Cub3** [comment]
Confirmed indeed setting up retry to a positive number will not get kissmanga stuck anymore and update are working, weird indeed, but working :) thx for your feedbacks @Vrosky and @StormJumper

**Comment by riderkick** [comment]
Not weird, -1 mean infinite as the caption suggest. And the server actually response with `503 Service Unavailable` which is in 5xxx server side error code. And request can be retry, because its considered temporary server error. That's where it fall to infinite loop.
