### ISSUE TITLE
checking favorites stuck

### ISSUE THREAD

**Issue by knucklerz** [riderkick/FMD#32]
![untitled](https://cloud.githubusercontent.com/assets/1240542/7772522/e505d634-00c8-11e5-90b3-2ee309730d61.png)
i just launched the app then it automatically check the favorites, then after it reached the end of the list it just stuck and nothing happen.. Also I can't close the app, because it's not responding..

**Comment by MammothJerk** [comment]
i seem to have the same issue

**Comment by riderkick** [comment]
Which version?
If you don't mind, give me your favorites.ini and config.ini. Those file is inside folder "works" and "config" respectively.

**Comment by MammothJerk** [comment]
Version 0.9.11.3
favorties.ini and config.ini = http://www.mediafire.com/download/car4dg7czc9az2v/favorites+config.rar

**Comment by riderkick** [comment]
I don't have any problem. I notice you set the mask task and thread to the max. Can you lower it. 4 threads per task is enough.

**Comment by MammothJerk** [comment]
i changed that, still crashes on launch

**Comment by knucklerz** [comment]
version 0.9.11.3
favorites.in and config.ini : 
https://goo.gl/xFOnh0

i tried copy my FMD folder to another PC and it experienced same issue
the issue somehow make me unable to close FMD gracefully.. when I pressed the close button the app became not responding and i must "tasskill" it throug CMD or Task manager..

**Comment by riderkick** [comment]
I see, it seems favorites thread can't be forced to terminate, thus make fmd to wait for it before closing the main process. This behavior occur when the server is to slow to respond, or give bad response, which causing fmd to retry to request the data as much as retry connect count on option>connection. Better set it to 3 or 5, don't set it to 0 (infinite).
In your case ba to to server often give bad response (503 service temporary unavailable), which causing fmd to retry infinitively (based on your retry setting).

I'll try to fix why favorite thread can't be terminated.

**Comment by riderkick** [comment]
@MammothJerk, it's crash after finish check or when you close the app. Do the button check caption turn to it's default caption? or it's still "Checking..."?

**Comment by knucklerz** [comment]
great! everything work smooth after the latest update and I changed the "retry" value to 5.. thanks

**Comment by MammothJerk** [comment]
its stuck on checking... for about a minute or 2 even after pressing the X to stop checking, if i try to close fmd during that time it will freeze and i have to close it with task manager

**Comment by riderkick** [comment]
@MammothJerk Have you try the latest version?

**Comment by MammothJerk** [comment]
yes i did this on the latest version: 0.9.12.0

**Comment by riderkick** [comment]
Does it still stuck. There is actual thread life with icon and highlight, you should know where it's stuck. And abort button should work now.

**Comment by MammothJerk** [comment]
it stops when i reach the manga from batoto, i've been having some problem with connecting to batoto recently so that must be whats causing the problem

so the favorites checking messes up when you cannot connect to the website specified i think

**Comment by riderkick** [comment]
Just like I mention above, ba to to server often busy/down. And if you set retry time to '0' it will retry infinitely until the server getting well again or interrupted by user(abort button). Set it to 3 or 5 to limit the retry count. I've set to 3  for default, but because you come from previous version, the config already altered.
But, abort button is working right? So, it shouldn't freeze when closing the main app.

**Comment by MammothJerk** [comment]
this is all with the latest version 0.9.12.1

i have been using the retry 1 time instead of 0.

when checking favorites for updates and if you cannot connect to the website connected to the favorite it will keep Checking... even if clicking abort for about 20 seconds.

![](http://puu.sh/hZf96/fe3117c72b.png)
ive clicked abort several times in this picture.

if i exit out from the application while it is Checking... FMD will freeze and have to be closed from the task manager. or i can wait about 30~ seconds for the checking jobs to finish and it will close by itself.


HOWEVER if you wait about 20 seconds AFTER clicking abort when its Checking... it will work as normal


it seems that clicking abort doesn't actually ABORT, it just waits until the current checking jobs finishes and then stops.



-the Abort button does not abort, it waits for the current jobs to be finished and then stops checking future jobs.

-if you try to close fmd while a Checking... job is running fmd will freeze until the current job is done and then close.

**Comment by riderkick** [comment]
Aborting favorites check is working fine here.
http://i.minus.com/jo5Hd4eZqj7vn.gif
