### ISSUE TITLE
e-hentai.org/exhentai.org possible overlong filename/path issue?

### ISSUE THREAD

**Issue by GramMKII** [riderkick/FMD#332]
task just keeps running, transfer rate indicates data is being downloaded but progress remains at 0/33 even after a while and when I check the chapter folder it remains empty.

sample gallery link
>http://g.e-hentai.org/g/958786/033f89507c/

my download path
> D:\Manga\

auto gen folder: on
remove manga name from ch.: on
auto gen chapter folder: on
manga folder name: %manga%
chapter name: %chapter%
filename: %filename%

resulting path (256 chars):
> D:\Manga\\(C89) [Pianissimo (Pija)] Honda-san wa Minna no _ Honda-san Belongs to Everyone (THE IDOLM@STER CINDERELLA GIRLS) [English] {CapableScoutMan & B.E.C. Scans}\\(C089) [Pianissimo (Pija)] Honda-san wa Minna no _ Honda-san Belongs to Everyone\\0000.jpg

Now I can temporarily fix the issue by setting the "Chapter Name" to _%NUMBERING%_ but I find it inconvenient to change this every-time I run into this issue since I prefer it to be set to _%Chapter%_ when downloading regular manga.

**Comment by riderkick** [comment]
I can overcome the limitation by using` \\?\`. But that seems useless. Because Windows explorer can't access it anyway. So does most of app. And you may find difficulties when trying to delete this files/folders.
Maybe strip out all the tags?
`(C89) [Pianissimo (Pija)] Honda-san wa Minna no _ Honda-san Belongs to Everyone (THE IDOLM@STER CINDERELLA GIRLS) [English] {CapableScoutMan & B.E.C. Scans}`
become
`Honda-san wa Minna no _ Honda-san Belongs to Everyone`.
Btw, you can setup another fmd installation exclusively for h sites, since they usually only have one chapter, you can disable auto generate manga folder. And you can store h and non h in different location.

**Comment by GramMKII** [comment]
I'd like to be able to keep the tags and using a different fmd installation seems like a roundabout way to solve this issue (i'm sorry <(_ _)>). I'm thinking would it be possible to make use of the advance.ini for per-site config overrides like for example
 > Options > Websites > Advanced > Config Overrides

then have

Website|Config
--------|-----------
Exhentai|GenerateMangaFolder=0

Thanks for the 'disable auto generate manga folder' tip btw.

**Comment by riderkick** [comment]
It's possible, but currently fmd running with hybrid website module, the new one is easily to initialize. But the old one will need some storage. That will just give more chaos in the source.

**Comment by riderkick** [comment]
As workaround, if the filename exceeds its available length it will be serialized. That way there will be no duplicate filename, and download will be working normally.

Btw, looking at the url you provide, the filename is perfectly fine, it's serialized number with max length is 4, so there's shouldn't be any problem. Maybe there is another issue, like bad connection.
