### ISSUE TITLE
sourceforge.net unwarranted packages??

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#350]
Wasn't there news back how sourceforge was loading unwanted software with the main software people were downloading from there site and they got flack about it? Putting FMD on sourceforge after this brewhaha won't look good for FMD. 

`“SourceForge are (sic) abusing the trust that we and our users had put into their service in the past,” according to the GIMP project. Since 2013, SourceForge has been bundling junkware along with their installers — sometimes without a developer’s permission.`

http://www.howtogeek.com/218764/warning-don%E2%80%99t-download-software-from-sourceforge-if-you-can-help-it/

**Comment by riderkick** [comment]
Bundling with installer only for opt-in developer. I never opt-in.
The problem of sourceforge is their intrusive ads, that fake download button. Careless user who just click-click without careful read may fall victim to it.
I only use sourceforge for file hosting. All the mangalist data is in there. Additionally its also mirror the release.
All the release is packed in 7z format, which shouldn't be touched by them. You will never need to visit sourceforge. It's just for auto update. The updater is just simply download directly the 7z file and extract it. There is no installer whatsoever. It's just the same as you do "download mangalist from the server", because all data stored there.
I can't find another free file hosting with direct link, sftp etc. If you follow fmd development, you may remember I used to host the file to another hoster, but it's not easy to manage, I have to visit their website to make a release, and even their rest api doesn't statisfy either.

About the bundled installer, there is actually a term and condition dialog which explain the service of bundled installer with accept and decline button. If you decline you will get the normal version. If you use adblock, you will never get this bundled version. If you browse throught "Files" and download manually your chosen file, you will not get the bundled version too.
Their owner have been changed, the situation maybe will change too. You better update your info, and check things first before make an assumption. Don't be like first day on the internet kid meme.

**Comment by StormJumper** [comment]
I know just thought I inform others incase they complain why is this other program installing with FMD. Well considering some major software like GIMP and others are no longer is on sourceforge that was something sourceforge did to themselves.

**Comment by riderkick** [comment]
When you download the setup from SF there will be a dialog about the bundled program with accept and decline blue button. If you don't see the dialog but still get the bundled installer then there is a chance it was the developers creation, then you will get the same anywhere you get it.
AFAIK bundled installer only for opt-in developer and for those who have single file installer/setup in executable format (exe). So basically the bundled installer is just the download tool, it offer to install unwanted software at starts then it will download the actual setup.
There is still many popular software that host their file in SF, like VLC, even thought it's not blatantly show the file in SF, when you download from their official website, you actually downloading from SF, they give the direct link to their file that shouldn't ever interrupted by SF. Just like what I did with updater.
FMD always been in SF since the beginning, the original FMD always been there.
My version is officially in GitHub, the SF mirror is intended to host the data, but it's not right to just host the data there, so I also mirror the release. They have download and statistics, so I decide to change the updater to SF. There's never been any installer of FMD, everything is portable. The updater simply download the 7z file and extract it. If SF ever go as far to redirect the direct link to any installer the updater of course will fail. So user eventually will resort to download the actual package, which is officially in GitHub. And there is issues tracker for user to report things.
If you afraid of term changed, then it's no different with GitHub too. No one know the future hold.
The condition right now is GitHub focus on developer, not user, so it's the release part is limited, they even encourage to host the release somewhere else. GitHub make money from developer with their private/corporate package. While SF in other hand have been shifted to focus to make money from users. That's where all commotions begin.

**Comment by StormJumper** [comment]
The conglomerate that bought SF did say they got rid of Devshare but that is in no way a guarantee in a for profit company that they won't in turn do the same thing. So if they had it in writing on the site for anyone to read and see and not change then they users would see if they were truly committed to what they say they intended. Money makes the world turn and buy Server space that is how it turns.

**Comment by riderkick** [comment]
There is no guarantee in internet except its existence.
It's the same with github, bitbucket, codeplex, gitlab and other service.
