### ISSUE TITLE
please add Dynasty Scans?

### ISSUE THREAD

**Issue by g4269159** [riderkick/FMD#36]
It recently implemented download limit, which is kind of annoying (it says 8 chapter per day, I can only DL 1 for some reason). Would it be possible to add it to FMD supported manga sites? Thank you!

**Comment by riderkick** [comment]
If they allow us to read their manga online without limit, maybe I can add it.
I'll look at it.

**Comment by riderkick** [comment]
I don't understand with their directory listing, which one should I adds?

**Comment by g4269159** [comment]
I'm sorry, I don't know. I guess all of them? Since there are 4 with different manga instead of just one (unless I'm missing something).

**Comment by abhishekanime98** [comment]
May I please add suggestion. http://casanovascans.com/ or http://www.readmanga.today/. Thank you ! If you don't want to add this to FMD. That's fine.  Thank you so much for the effort :) Thanks

**Comment by riderkick** [comment]
@abhishekanime98 Please make a new issue for that. Don't comment unrelated issue! Keep the thread clean.

**Comment by abhishekanime98** [comment]
Ohh! My bad. I am really sorry about that. :)

**Comment by MammothJerk** [comment]
Yeah the dynasty reader has an unusual system for sorting their manga with anthologies, doujins, issues and series.

series is probably the main category to add since it has the most manga out of the categories.
If youre going to add all 4 maybe name them Dynasty anthologies, Dynasty doujins, Dynasty issues, and dynasty series

if you feel like you it, you could also add a topic in issues for people to request websites to add to the program

**Comment by riderkick** [comment]
What I don't understand is some item can be part of another item. Like series and doujins can be part of issue. We need the actual root series which doesn't overlap each other. There's item what should be "chapter" in FMD, we can't add it as root series. We just need the root of the series. Please check it for me.
