### ISSUE TITLE
Downloads stop randomly when one or two files remain

### ISSUE THREAD

**Issue by quarkrj** [riderkick/FMD#364]
Whenever I try to download a manga, when for a chapter one or two files remain (eg 33/35 or 34/35), downloads stop (d/l speed - 0 KBps) abruptly sometimes. It happens multiple times in a download ,in separate chapters but as far as I can see its random. Stopping and resuming task fixes the problem temporarily. I usually download from mangahere, but the problem was also there in mangafox so I don't think that's where the issue is. Connection Settings - 

No. of d/l tasks at a time - 1
No. of downloaded files concurrently - 8
Connection Timeout - 300
No. of retries - 5 (tried with -1 problem still there)
No proxy.

My internet has no problems that I know of. I use windows 10 build 1607. And this is my first time using github so sorry if I annoyed you :p

**Comment by StormJumper** [comment]
You need to provide what manga series for others to test and reproduce the same problem to verify there is a problem first.

**Comment by riderkick** [comment]
Give me your works.ini.

**Comment by riderkick** [comment]
Some possibility for your issue is due to temporary server issue. Maybe the server is exhausted, so it's stuck without reply. And your connection timeout is too high, lower it to 30 or 15, or even lower if you had fast internet speed. 300 mean 5 minute, so it'll wait for 5 minute until the server reply. Then repeat the request(depend on the number of retries) if there is no response from the server.
Lowering it will make the wait time become shorter, so it will break the connection sooner. Then repeat the request if retry count <> 0.
You have to take into account some server does have low ping/slow response, like bato to, so 10 or 15 is recommended.

**Comment by quarkrj** [comment]
[works.txt](https://github.com/riderkick/FMD/files/437293/works.txt)

here you go. As I said it's random, but you can try to reproduce the problem. I had the problem when downloading Black Haze , Koe no Kitachi , Re : Marina maybe more I don't remember. I renamed ini to txt to allow upload. I will try your solution too.

**Comment by StormJumper** [comment]
I see you using 0.9.77.0 have you tried the latest version?

**Comment by riderkick** [comment]
I recall there is a similar issue in issue tracker, the problem is due to not synchronized threads, but that issue have been fixed a long time ago. I'll try to search the issue tracker. 
Seems like the title doesn't match the content. This is the reason I strongly suggest the reporter to split their report to a few thread if they have many issue, and don't bundle it to 1 thread. Also make a proper title. Make it harder to search later.

**Comment by riderkick** [comment]
When the issue occurs again please take a note how much the threads is running via `Task Manager> Process>fmd.exe`, look for `Threads` column.
Stop other running thread, and make sure only the troubled download running, stop all favorites check/update check or other thread. You can take a screenshot of fmd and your Task Manager window to make it faster.
Or better, you can use [HandyCache](http://handycache.ru), and set fmd proxy to its listening port(8080) with ip 127.0.0.1. Then you can see all of fmd connection in handycache window. When the issue occurs if there is still connection in handycache but just stuck, then the problem is on the server(can be throttling issue), but if there is no connection then the problem may be in fmd.
