### ISSUE TITLE
Possibility to add "delete task + data" to the "delete all completed tasks" button

### ISSUE THREAD

**Issue by Beylers** [riderkick/FMD#366]
Maybe as an extra option that you can turn on, that changes it so it also deletes the data. I read a lot of Manga straight out of FMD and then delete them immediately after reading them, that option would save some time.

**Comment by riderkick** [comment]
Not a good solution. I decline this because it's more to personal use, and not much of use. There will be many request for personal use. The options are already crowded. More code more harder to maintains.
I only accept for basic function.
You can filter the download by status, Select all (CTRL+A) and use context menu instead.
That save some time you're talking about is just a mere a few seconds. Unless you use it hundred of time a a day, that's shouldn't waste your day.
