### ISSUE TITLE
Suggestion - image crop and fix the white

### ISSUE THREAD

**Issue by M9k** [riderkick/FMD#371]
It's only a idea, what do you think about the possibility of auto-crop the image and fix the white if they are gray?

**Comment by riderkick** [comment]
The hard part is to detect the gray color, Many image that is jpeg doesn't have truly gray color, sometimes they are distorted and just look like gray with human eyes while in fact they are not, Especially the old scan. They are a bit to red or blue and not flattened. Or even a shadow from bad scan practice. I think this is the kind of Image you want to fix.
Cropping the white space is easy, but again, with low quality scan, that will be not effective too.
Also take into account every time we edit an image, the size usually will be larger, even though the dimension become smaller. Because we deal with raw image and doesn't know the original compression. All of the pixel is complete independent color. Except if the image can be detected as gray with its metada, we may can achieve very close file size with the original.

**Comment by Efreak** [comment]
This could be done by having a script that can be run on the files. Just add a setting to the 'save to' box. It should run in (initial working directory) the main manga folder for convenience. An example would be using [imagemagick](https://www.imagemagick.org/script/mogrify.php) to [autocrop](https://www.imagemagick.org/script/command-line-options.php#trim) all images, and save all jpegs with a lower quality.

script: c:\programs\fmd\fixfiles.bat
```BAT
REM /b = format bare, /a-d = no directories, /s = recursive
for %ss in (dir /b /a-d /s *.gif *.png) do (
    REM trim images.
    mogrify -trim "%%s"
)
for %ss in (dir /b /a-d /s *.jpg) do (
    REM trim images and save with lower quality.
    mogrify -trim -format jpg -quality 80 "%%s"
)
```

There's other options available to `mogrify` (and the `convert` command as well), and likely other software out there that takes images by command line for processing.

Allowing a script would also allow for saving in other formats (call tar for cbt, move files to calibre auto-add folder when done, etc)

Alternatively, if you wish to do things yourself (outside the software), you could check out [CbxConverter](http://tomeko.net/software/CbxConverter/) for a GUI, since it's built around imagemagick as well. You'd have to set FMD to save as CBZ files, but those are just zip files and can be extracted when you're done, if you want a different format.

**Comment by riderkick** [comment]
I think this issue should be handled by the comic viewer directly rather than modify the file. Many comic viewer had this feature already. Modify the file directly will make the original image unrecoverable.
