### ISSUE TITLE
Listing for Sites Failing to download

### ISSUE THREAD

**Issue by JingJang** [riderkick/FMD#377]
Hello,
Thank you for this app. A few out of date plug-ins. Tested all the English sections and the following listings have failed:
- FunManga
- KivManga
- MangaHen
- MyMangaMe

Also raw site that failed
- RawSenManga (Please fix this one)

From the adult section, only tested a few and almost all the ones I tested failed. Including XXComixMT and XXComix3D, and all the ones the begin with "Porn". Even when the listing is downloaded the links are all wrong and you are unable to download. It causes a crash.

**Comment by StormJumper** [comment]
I had no problem with those you listed for EN downloaded listing just fine. How are you updating them?

**Comment by JingJang** [comment]
I just select it from combo box and I get 404 file not found error.

I am using version Version : 0.9.83.0




<pre>
[Window Title]
Error

[Content] 
File not found!

Response: 
404 Not Found
[OK]
</pre>

**Comment by StormJumper** [comment]
Give a specific version of manga and I'll see what if the download gives a error. But I know when I download all the manga updates including those you listed it works fine. A clean install will not fix a problem if it can't be replicated.

**Comment by JingJang** [comment]
> Give a specific version of manga and I'll see what if the download gives a error.

I am unable to download the listing so I cannot give you any specific manga. There are ZERO manga for me for the following sites: FunManga, KivManga, MangaHen, MyMangaMe. and RawSenManga.

Does RawSenManga work for you? I would really like to get that one working.

>  A clean install will not fix a problem if it can't be replicated.

A clean install is the way you replicate it. Without the listing I do not get to the stage where I can select a manga. Maybe when I have the listing downloading the manga is no issue. 

I have just tried another clean install and I tired to download the listing for the very first time for the sites mentioned. It failed on all occasions. 

I tried using the 32bit version and the 64bit version on Windows 10 (64bit).

**Comment by StormJumper** [comment]
Listing showing for them: FunManga, MyMangaMe

Some list show and some blank: MangaHen

List showing but no download: KivManga(might  be offline or changed)

I have Windows 7.

**Comment by kavin-90** [comment]
MentalManga use OMV 1.4 version same as Sen Manga, Raw Sen Manga

**Comment by sgn15** [comment]
Hi, using the "download list from server" does not work for these sites as of Sept 20 2016 (version 0.9.83.0)
FunManga
MangaBackup
MangaHen
MangaIce
MangaKoi
MangaOnlineTo
MyMangaMe
SenseScans
TripleSevenScan

*I only checked English and English Scanlation websites so there might be non-English sites not working too.

I tried the "update manga list' for FunManga and it already took 3+ hours and it still hasn't finished. I cancelled it.

I would like to ask if there are files of these sites ready to download normally through browser rather than through FMD. I actually used my old files for other sites (found them from my old FMD 0.9.6.3 in my old HDD) and updating already existing files actually work better than downloading for no-lists-yet websites.

Thank you and more power to the people developing FMD.

**Comment by StormJumper** [comment]
@sgn15 , what are you update settings?

**Comment by sgn15** [comment]
I was previously using FMD I got from the comments section of akarink's site so I am kind of new to the github version of FMD and these settings are new to me. Here are my settings.

Options>Updates
^this? (I checked the "Don't load manga info (filter won't work)" checkbox)
But I checked the auto-download latest FMD update

Options>Websites>Advanced
*or this? (I don't know/understand what all these settings under this are for)

I tried MangaHen now and it is also just as slow I think as FunManga. 30+ mins and still not even 1/8 updating done? I'm just asking this because I don't know the usual working speed of this.

Thanks again.

**Comment by StormJumper** [comment]
@sgn15 Does your setting in the screen shot have the 3rd box "number of retires" as how much? And what is your timeout connections?
http://www.softpedia.com/get/Internet/Download-Managers/Free-Manga-Downloader.shtml#sgal_6

**Comment by alvarexoz** [comment]
hey, i can't download in yomanga.co
![fail in yomanga](https://cloud.githubusercontent.com/assets/17180171/18749647/1bb7d8de-8102-11e6-9aae-f9cb26aaee25.PNG)
Look, no checkbox on it
please, fix this problem

i will update those site which can't be downloaded from them.
Thank you, Cc : @riderkick

**Comment by sgn15** [comment]
@StormJumper 
I'm sorry I don't understand your post. There is no screenshots in either of those links? I'm also not sure what/which icon you are referring to in that link. Anyway, I can't find a checkbox called "number of retires" anywhere in my FMD 0.9.83 

I tried updating manga lists again today (one by one, not the update all manga list button), all seem to work now except MangaIce (no manga in MangaIce list, update doesn't work, no manga list in server too). So yeah, as of now, MangaIce is the only problem. I don't know what fixed all the other websites.

My timeout connection is 30 seconds.

Sorry for all the trouble. Thanks again for responding and helping.

**Comment by StormJumper** [comment]
@sgn15 did you follow the site and find the screen shot matching what I said? you have to click on the icon to and scroll to the right one to find the one I am referring to.

**Comment by sgn15** [comment]
@StormJumper 
ok I followed the settings values you have now. It's still the same issues with my most recent post (MangaIce has no mangas, EyeOnManga gets stuck in "Getting directory" while updating). The rest of the websites (English and English scanlations) are working now with update manga list button.

**Comment by StormJumper** [comment]
Those values are from the site they are not my setting...you need to set the first to box half of the limit and the last box at least 10 so it will update properly.

**Comment by sgn15** [comment]
Ok my values are now set to (from top to bottom) 4,1,1,10, I tried the "update all list at once" and it didn't get stuck at any website and finished on its own, but MangaIce still has no mangas on its list. EyeOnManga seems to be fixed now.
