### ISSUE TITLE
please add support for this manga sites

### ISSUE THREAD

**Issue by rcarlos243** [riderkick/FMD#4]
not really an issue but please add support for:
manga.redhawkscans.com
imperialscans.com/
reader.cafeconlenin.com
luscious.net/

If possible, can you also add a feature where the manga infos on FMD tab (for individual manga that is added to download or favorite) shows the picture, name, author, artist, genre, summary  be integrated/downloaded with favorites or download history so that when I am looking at my favorite list  or download history (by either right clicking it and show info or pointing my mouse pointer to a manga it would show the manga info), I have an idea of what I am looking at especially If I have tons of them?

**Comment by riderkick** [comment]
Sorry no feature request at the moment. This project came to maintenance mode only. I just change the thing to make sure it's still working. There is more than 80 supported sites on FMD, you may found what you're looking from another sites.
I've been thinking to store manga info to favorites and show information as ballon hint. Unfortunately there is no simple way to do it with current development tools. And I don't have time to write all the required stuff from scratch. So I drop it for now.
If you're able to implement it, feel free to make a pull request, I'll be happy to merge it to master branch.

**Comment by blue-lightning** [comment]
You probably should put that comment into the readme.txt, so people won't ask for more manga sites again in the future. That's a shame thought.

**Comment by riderkick** [comment]
Actually it's the same rule as akarink before. No more than 5 site per language. And no more english site, because there is already more than 80 sites.
I may replace the dead website with the new one. But keep in mind, there is just one dev right now, so be patient.

**Comment by blue-lightning** [comment]
Well, opening a new issue for a new site right after you explicitly said not to request for new sites is just... And I see you wontfix the Starkana removal issue, so site removal is also out I guess.

**Comment by riderkick** [comment]
I'll not add new english site because there is already too many to maintenance. FMD doesn't work like plugins for supported sites. It's planted directly to the core. So it become more complicated with more website support.
But, I can replace the website if it was dead and there is no alternative in current supported sites.
The same rules as akarink no site more than 5 per-language.
Starkana labeled wont-fix because it can't be fix, the website is dead.
This is open source project so you can contribute, make a pull request,  I'll be happy to merge useful changes.
I don't have time to add more sites, especially if there is still alternative in currently supported sites.
That's my personal decision, sure anyone can add more site if they like.
