### ISSUE TITLE
alternative

### ISSUE THREAD

**Issue by shogunreaper** [riderkick/FMD#417]
anyone got an alternative?

i was using domdomsoft and then this but both are now dead.

**Comment by amayra** [comment]
you can use [MangaRipper](https://github.com/NguyenDanPhuong/MangaRipper/) by @NguyenDanPhuong

**Comment by shogunreaper** [comment]
eh it only supports a few sites.

**Comment by amayra** [comment]
how about [HDoujin Downloader](https://doujindownloader.com/) you can try demo is free ?

**Comment by shogunreaper** [comment]
yeah i saw it but you have to buy it or it will have limited downloads.

**Comment by amayra** [comment]
so i think is your only option left is to join us and wait @riderkick to come back 
ps: if you find any alternative tell me

**Comment by NguyenDanPhuong** [comment]
Hi, I'm the one who made MangaRipper. It is a bit difference than others tools. I've been focused on stability, good code quality not on support wide range of sites.

With the current design of MangaRipper. I can add support for 1 more site in 30 - 40 minutes working time. 

I'm not focusing on support new sites but if that site really bring more value (like image quality, not just be another sites) I may do it. Or anyone with a little programming knowledge can do by send me a pull request.

**Comment by StormJumper** [comment]
I am a user of FDM and once DomDomsoft closed lucky I didn't buy it yet but was deciding. I will say the price to pay for lifetime on HDoujin is worth it. I bought it because the price was not so high that you couldn't afford it. We all have to come to reality doing such programs takes time/money/labor to do so paying for something like HDoujin is worth it in the long run that the Author knows their user based will remain with them. That a incentive to keep the project going and if FDM ask for donation to keep going we all should do our part. Nothing should be taken for granted for Manga download reader. Just like fansubbers asking for donation for their time/effort to make it for those in different language read to read Manga and enjoy it - I myself in 2017 will consider making donation to fansubbers that I like to keep the projects they do going for the small price to pay to enjoy manga. If one consider all the manga that you had to buy and some not available in your Region this FDM and fansubbers donation is a drop in the bucket in the bigger scheme of things.

**Comment by kavin-90** [comment]
I use FMD for grabbing Raws from Official Websites btw i use own Build i've no knowledge of Pascal so copy and paste works 😄

**Comment by StormJumper** [comment]
@kavin-90 same here I update my FDM manga list even if the Author just to keep them up to date on manga updates. And still worse at any pascal programming. :(

**Comment by kavin-90** [comment]
Soon i gonna add build on my Repo they might be broken somewhere still good than nothing.

**Comment by kavin-90** [comment]
@StormJumper and all FMD fans try this Patch Version

[FMD-Patch](http://www.mediafire.com/file/588zywc2wb1blea/FMD-Patch.rar)

**Comment by amayra** [comment]
@kavin-90 thanks you but did you fix MangaTown and MangaFox in this patch ?

**Comment by kavin-90** [comment]
I did i try MangaTown it work not MangaFox . You can track what is changed in My Fork Repo

**Comment by liohunter** [comment]
@kavin-90 Thank you so much for keeping this updated! Will the built in updater work for your specific fork? Alternatively would it be possible to set up a github releases page for your updates?

**Comment by shogunreaper** [comment]
@kavin-90 

where do you release builds for it at?

**Comment by kavin-90** [comment]
i posted here mediafire links my build copy so i don't think i need to build release pages.

**Comment by StormJumper** [comment]
Tried the mangafox fix patch and it crashed when updating manga list. So went back to the original FMD.

**Comment by StormJumper** [comment]
If crashed when I did a all manga list checkup date it would load and start the update but it would eventually slow and then stop and crashed. It was all the EN manga list with all the manga checked including a few new one. Right now I am using MangaHere for my updates.
