### ISSUE TITLE
Kissmanga "Failed, try resuming this task"

### ISSUE THREAD

**Issue by cassiusclayman** [riderkick/FMD#435]
I've tried multiple versions and searched through issues trying to find a solution but nothing has helped, unfortunately; whenever I try to download anything from kissmanga the download will fail after about half a second. I've increased both the number of retries and connection timeout duration to no avail. On the other hand, mangahere works.

**Comment by Inareous** [comment]
Hey, might i ask you to try something to identify the causes ?

1. Try to access KissManga.com using your browser, Firefox or Google Chrome are preferred.
2. Open any chapter from any manga, to test that the site working as intended.

From here on, you may either redirected to "Are You Human" page, asked to verify yourself by solving the captcha or you redirected to the chapter page itself.

If the latter happened, can you see the image of that chapter ?

Also, try checking your FMD config, referring to  issue no #426 and #433 (in config.ini or Connections tab)

**Comment by FormisSage** [comment]
Started happening to me too after downloading a certain amount of chapters yesterday, since then it always failed immediately after "Preparing" the queued chapter without downloading anything. The website works fine in a browser (both Firefox and Chrome), passed the anti-bot protection, chapters display correctly, just FMD fails.

However, I tried proxy and it's working again so it might be related to #426 (too many requests from one IP, IUAM)?
Probably not #433 related, it fails and doesn't seem to be retrying, has to be resumed manually.

Also, not sure if this might warrant a separate issue, but deleting this failed task "as is" freezes FMD, has to be shut down from task manager. Disabling it then deleting works fine.

**Comment by Inareous** [comment]
@FormisSage 

> Also, not sure if this might warrant a separate issue, but deleting this failed task "as is" freezes FMD, has to be shut down from task manager. Disabling it then deleting works fine.

You should create another issue ticket for this.
Actually, it will only freeze if you delete running task, deleting stopped task will not trigger the freeze event.

**Comment by Askael89** [comment]
I'm having that problem with all the downloads and also when downloading various chapters of the same series if i resume it will take the downloaded pages from the previous chapter and take them as if they were for the next instead.
