### ISSUE TITLE
Porting to GNU/Linux

### ISSUE THREAD

**Issue by ReksaTresna** [riderkick/FMD#448]
Can you port this app to GNU/Linux?

**Comment by matoro** [comment]
I have tried this without success so far, though theoretically, you should be able to build it simply by following the build instructions in the README via Lazarus, which runs natively.  Luckily, FMD runs excellently under WINE, with the exception of the updater, which must be done manually.  Other than that though, I have been running FMD under GNU/Linux for over a year now without issue.

**Comment by StormJumper** [comment]
That will be alot of work to port over since were talking about different O/S and since Windows is more common unless there be more financial support for them to port over to another O/S this will be short in coming. Also as matoro said it works fine in WINE so then that should be the option to use and for updater I just check and download it manually and then copy the data to the new version and it works fine.

**Comment by riderkick** [comment]
You can try to compile it on Linux. Maybe some code need to be change, but I'm sure most of the code is compatible since I've been changed a lot of code from windows specific to fpc compatible.

**Comment by matoro** [comment]
@riderkick - I am interested in giving this another shot, with a little bit better knowledge of Pascal and general lower-level OS stuff.  Reading through the code, I've noticed you have made some attempts to keep things platform-independent (quite a few ```{$IFDEF WINDOWS}```) but other portions are *very* heavily entrenched in Windows-specific stuff.  For example, ```frmDropTarget.pas``` is pretty much unportable.  If I am successful, the resulting binary will be rather crippled but hopefully functional, and I'd be more than willing to see about cooking up an OSX binary as well.  A multiplatform release for FMD would be a great achievement :D

Anyway, if you have the time could I use this issue as a place to post questions, track progress, etc (unless you'd prefer somewhere else)?  This would of course be low-priority compared to fixing critical bugs, especially since it works flawlessly on WINE as of a few months ago, but a GPL-licensed program feels like a waste without a native Linux port :)

**Comment by riderkick** [comment]
`frmDropTarget.pas` currently only work for windows. It is using ActiveX I don't know how to implement it on other platform. Just disable/comment or add `ifdef` for all of that Windows specific. You can look at virtualtreeview components, I think it has Unix and OSX drag n drop support. It is used in downloads list and favorites list.
Yes, you can use this issue or create another issue for discussion.

Currently I'm experimenting to integrate lua for website modules. So we can add/edit at runtime without the need recompile everything. But not gonna happen soon. Still need a lot of work.
