### ISSUE TITLE
"Checking favorites" result stay visible?

### ISSUE THREAD

**Issue by spamtaztik** [riderkick/FMD#467]
Currently after the program finished checking for new chapters, the marks (checkmark, green dot, etc, pink background) disappears after finished checking the last favorited manga right? 

Can you make it so that the result stays visible EVEN after it's finished checking? This way I can see if there are any -old- chapters that I miss for any mangas, and I can go ahead and download them.

Thanks much.

**Comment by riderkick** [comment]
That one tied directly to the status of favorites. The icon and background automatically changed when certain event triggered. The status is important for check update's thread to identify which one need to be check or which one have been done checked. Due to current design of fmd which allow individual favorite to be checked so the status must reflect the actual status of favorite.

**Comment by spamtaztik** [comment]
Hmm, alright then. Just thought I'd ask. Thanks.


-----Original Message-----
