### ISSUE TITLE
Download speed problem

### ISSUE THREAD

**Issue by Souravi785** [riderkick/FMD#471]
Download speed drops to 0 after a while and I have to stop and resume it again and again. This problem occurs almost every time I download a chapter. It's a little annoying. Can something be done? 
And btw I don't think there are any problem with my broadband.

**Comment by kavin-90** [comment]
Problem is not on FMD side it comes from either website or isp side.

**Comment by Souravi785** [comment]
But there's no download problem in Domdomsoft. I tried using the same site in Domdomsoft after using Fmd.

**Comment by StormJumper** [comment]
@Souravi785 Domdomsoft is dead-so not sure where your info is coming from but it is no longer there. So there is nothing FMD can do about Domdomsoft problems.

**Comment by Souravi785** [comment]
Hmm, I know domdomsoft's site is dead but domdomsoft still works and I am using domdomsoft. I used goodmanga in Fmd and the same site in domdomsoft but speed problem occured only in Fmd. But still if there's nothing to be done then it's fine. It's a little annoying but I will try to use Fmd as how it is.

**Comment by riderkick** [comment]
You should give the example. The website, series, chapters. All of it may matters. Some website is slow like batoto, some other refuse if there are too many connections like mangafox. And many other websites has their own behavior.
Often if there is no connectivity, speed is 0kbps but status in "downloading" it just simply waiting for the respond from the server.
Another thing you can do is lowering your connection timeout and increase your retry count, maybe like 10s or 5s with 50 retry count. That way, fmd will drop the connection if there is no respond in 10s, and will retry with a new request. This depends on your internet speed of course. But be careful don't set it too low, because some website like batoto indeed having slow respond. Or you will end up without being able to download anything because it will always break the connection without giving the server enough time to respond.
You can try to use handycache (just disable the caching feature) and redirect fmd to its proxy listen port. From handycache you can monitor the connection fmd made. You will see if there is stacked connection.

**Comment by StormJumper** [comment]
@Souravi785 Last I tried at the end of 2016 the site doesn't exist and was up for purchase. You can't download update when the site is gone.

**Comment by Souravi785** [comment]
@StormJumper Sorry, I don't understand what you're saying. I know the DMD site is gone but I still can use DMD. It's been a few months since I am using it. And kissmanga, mangasee, mangago doesn't work. But batoto, goodmanga, eatmanga, mangafox, mangahere...etc works. And updating those working sites are fine as well.

**Comment by StormJumper** [comment]
I've used FMD for some time and never had download problems other then the site blocking FMD.

**Comment by Souravi785** [comment]
It's fine now. Thanks for the help everyone. Reducing the timeout and increasing retry worked.
