### ISSUE TITLE
[ Issue] Nhentai.net Blocked in mycounty 

### ISSUE THREAD

**Issue by kunavut** [riderkick/FMD#525]
I can't download on FMD. Please help.

This website contains information and inappropriate. 
Suspended by the digital economy and society.

**Comment by riderkick** [comment]
Use proxy or vpn.

**Comment by kunavut** [comment]
VPN dont work i will try proxy Thanks.

**Comment by kavin-90** [comment]
or use http://googleweblight.in/

**Comment by Hexaf** [comment]
or use simple dnscrypt

**Comment by riderkick** [comment]
dnscrypt is useless in my country, because most of the isp also block the ip.
even worse, my cell provider also intercept the web request. they randomly put a landing page.
and the ads when using their internet is worse. intrusive to the max, and just one accidental touch I will lose money without I even know it. They automatically add my number to their content subscription without prompt, charge me a lot for stupid contents that we can freely find in the internet (wallpaper, ringtone etc). 
so only vpn can save us. but even so some isp also block certain port, like 1194 for vpn. that's why there is a lot of unusual vpn port in my country, like 80 or 443.
I don't know how our government keep silent about this, when a lot of people complaining. I guess they got a lot share of money.
