### ISSUE TITLE
kissmanga still not working

### ISSUE THREAD

**Issue by hlaxkar** [riderkick/FMD#549]

**Comment by molitar** [comment]
This has been fixed. But you have to start a new download the failed downloads do not have the correct URL for download.  Right click on each failed one and select view manga info.  Now click on all green highlighted chapters and press download.  Repeat for all failed chapters than delete the tasks only of the failed chapters.

**Comment by Lelouch101** [comment]
I need to add on this. Mine isn't working either.
The manga information are fetched normally along with the chapters, but not for the chapter's pages. I also tried to download other manga but it also doesn't work. 

Are there additional steps to follow to make the decrypting work cause I think that's where the problem is right now.

**Comment by danielbintar** [comment]
+1

**Comment by hlaxkar** [comment]
nope not working tried adding new manga but no page is downloading

**Comment by riderkick** [comment]
Move to #538
