### ISSUE TITLE
Exit Confirmation Always Show Up

### ISSUE THREAD

**Issue by danielbintar** [riderkick/FMD#553]
when I click Free Manga Downloader Icon in the windows taskbar

**Comment by Tmp341** [comment]
Yep, confirmed. If fmd window is open, no problem. But if it is minimized to tray, and you double click on it, exit confirmation shows up.

**Comment by Tmp341** [comment]
And, i unchecked "exit confirmation dialog" and boom, fmd closed itself on double click.

**Comment by hlaxkar** [comment]
same here fmd is closing itself on maximizing from the tray

**Comment by Leguron** [comment]
I also have a new problem after the update. Whenever I want to maximize Free Manga Downloader the confirmation windows pops up and is asking me if I want to close the application.
When I deselect the "Show dialog confirmation for Exit FMD" it automatically closes Free Manga Downloader when I want to maximize. Did I fuck something up in the settings or did the update change something so that maximize is the same as pressing on the red X? I don't know if I should opne a new issue.

**Comment by riderkick** [comment]
Apparently,  there is a bug with lcl.
