### ISSUE TITLE
[Issue] KissManga Slow New Chapter Check

### ISSUE THREAD

**Issue by marstaik** [riderkick/FMD#569]
So, the only Manga on my list that take forever to check for new chapters are those from KissManga. It hovers around 0-1% CPU utilization while its doing this. They do eventually go through but it takes forever, > 10m to do so.

Sometimes it hangs for so long, closing and reopening the application is required in which it will return to normal speed, although still a bit slow compared to other sources.

I don't have any error logs, so I don't know whats up.

**Comment by StormJumper** [comment]
What version of FMD are you using? To be sure it's not a site issue did you go to KissManga to read the same manga your download to see what happens?

**Comment by marstaik** [comment]
When I went to the actual site, the pages and info pages loaded instantly. The eternal hang seems to have disappeared for now, but it still takes forever to check for new chapters on those sources.

**Comment by 7h3Cub3** [comment]
This is a known issues, when you keep FMD running 24/7, after a while, you can't check kissmanga anymore (favorites chapter count is 0, and no new chapters pop-up) a restart of the app solve this, when i spoke to riderkick about this quite a while ago, if i remember correctly, it was something related to their site browsing protection (cloudflare or something) and the ID/cookie of the http grabber that was embedded into FMD to download/check mangas. A restart will flush out any trace and it will work again. Dunno if it's fixable by programming, in the meantime i made a script that i start twice a day with task scheduler, that will close FMD, and restart it so that everything is flushed neatly. No more issues since then.

**Comment by marstaik** [comment]
I never keep FMD open in the background though, I always open it like once a day and thats it.
