### ISSUE TITLE
[Suggestion] Option to Auto Start with Windows in Tray

### ISSUE THREAD

**Issue by Eisa01** [riderkick/FMD#574]
Hello,
It would be great if we had the option to auto start FMD in windowz tray when turning our computer on.
Thanks!😊

**Comment by StormJumper** [comment]
You can also do that by making a shortcut in your "startup" folder that will also do what your asking as well. I'll have to double check but I thought there was already that option.... And it does help if you tell us which version you asking about.

**Comment by Eisa01** [comment]
+StormJumper
I'm running the current latest release 0.9.109.0.

I hope it can be supported natively (^ ^)

**Comment by 7h3Cub3** [comment]
There is an option to minimize to tray, but it does it only when you minimize the window yourself, not at start, +1 this to have something that allow you to start it minimized for starting @ windows boot, the startup shortcut is a solution, another one would be to add a checkable option in FMD option to add the entry in the windows registry so that it start @ boot. You can in the meantime as StormJumper said, use a shortcut in startup, where you edit the shortcut properties to run it as minimized (you can also use of course the same shorcut on your desktop or menu bar) it work nicely :)
