### ISSUE TITLE
I can't download any lists: "Failed loading page!  Response: 500", version 0.9.110.0

### ISSUE THREAD

**Issue by VickGE** [riderkick/FMD#588]
https://vgy.me/DYz2x4.png I can't download any lists apparently,  I just downloaded 0.9.110.0.

**Comment by mufeed20** [comment]
More info might be useful. Like platform or operating system.

**Comment by potanx** [comment]
i have the same problem, every time i try to download list or download update new version alwayas failed since the frst time i use FMD, it's version 0.9.86 i use the 64 version.7z i extract and open the fmd.exe
my os windows 7 ultimate 64 i use simple dnscrypt too. what should i do so i can download new version from the program or list work?

thanks

**Comment by VickGE** [comment]
downloaded a build .exe, I'm on W7.

**Comment by StormJumper** [comment]
I have no problem downloading FMD which link did you use?

**Comment by VickGE** [comment]
I don't have any problem to download FMD, I can't download any lists.
