### ISSUE TITLE
UI needs to be fixed for high resolution desktops

### ISSUE THREAD

**Issue by iaminvincible25** [riderkick/FMD#600]
I have a 4k monitor and when I start the software all the UI elements are scrambled, and I can't see chapters list (I think they are related)
![image](https://cloud.githubusercontent.com/assets/28995729/26518778/badb4a86-42cc-11e7-8c63-3200753c8250.png)

**Comment by riderkick** [comment]
You're using very old version of fmd. Try the latest from releases tab.
I don't enable the high dpi awareness because I need to adjust it accordingly to various size, and I don't have the devices to test. But with current manifest with 96dpi, windows should stretch them out just like your unity app in the background. May appear a bit blurry, but should not be apparent if your monitor not too big.
