### ISSUE TITLE
Update from 0.9.115.0 to 0.9.117.0 not working.

### ISSUE THREAD

**Issue by Leguron** [riderkick/FMD#614]
Free Manga Downloader trying to update and then displaying the error "Invalid URL".

Is there a way to fix it? Also where can I download free manga downloader already updated to 0.9.117.0?
How would I import which series I bookmarked?

**Comment by Meliodas-Sama** [comment]
You could Download FMD from [https://sourceforge.net/projects/newfmd/files/?source=navbar](url)
Select Your windows type ( 32 or 64 ) bit and then extract the compressed  file into FMD Directory Folder.

**Comment by Leguron** [comment]
Thanks for the link. I'll look at the release and see what I need to import from 0.9.115.0

**Comment by Lmmb74** [comment]
Release 0.9.117.0 says the following:
Fixed empty update url, you may need to download this version manually
https://github.com/riderkick/FMD/releases/tag/0.9.117.0

**Comment by riderkick** [comment]
There is a bug in 0.9.115.0 which make fmd doesn't store the update url to the right variable.  So, fmd doesn't send the updater url to the updater.exe.
Regression by https://github.com/riderkick/FMD/commit/3c954d95de19745bbd5a4da75cfe5ae74dfb583e and fixed by https://github.com/riderkick/FMD/commit/92aa94c9860902643e496a0b4bc7f4502275c42f
