### ISSUE TITLE
[Feature Suggestion] Option to add or remove sites manually by the user 

### ISSUE THREAD

**Issue by Twoearle** [riderkick/FMD#617]
Taking a quick glance at the "issues" page of FMD makes it apparent that many requests involve adding or removing certain sites to download content from, but there's only a few contributors to the project (with riderkick doing most of the work) so it might be a good idea to search for a more systematic solution. 

One alternative would be adding an option for users to manually add/remove/update sites, maybe with the aid of a graphical interface that helps with some of the steps; of course this would only have local or user-side consequences, as it should never be considered an official update unlike a commit from the repository. This way, if you want FMD to download something for you from a obscure or not well known place, you could add it yourself with the benefit of making the maintenance process somewhat more manageable. 

Another feasible way is to write some documentation in a README file or the wiki, explaining how to do it even if it might require some more technical knowledge. 
Thanks for your time!

**Comment by riderkick** [comment]
Every website is unique, there is no universal way which you just can work with them easily with template. You have to write the precise step to parse them.

I have been experimenting how plugins work years. dll need a lot of work. and since it uses a lot of other unit the size would be problematic. versioning also another problem. pascalscript or lua also need a lot of work to publish all the method. and they only run once. pretty much like executing small progam. manage memory share is so complicated with multithread. to much details, to much work. unlike java which can load the class at runtime. I want to cut the modules from the main program, so user can update separately. But I can't find the way yet. lua or pascalscript maybe the way, but it's so complicated to integrate. Especially how many thread will manage them and share the data.
