### ISSUE TITLE
Madokami problems

### ISSUE THREAD

**Issue by Souravi785** [riderkick/FMD#636]
There are many problems i'm facing with madokami. First of all the i can't update the manga list,I have to download the list from the server and even after that many manga is missing(madokami is suppose to have a big collection of mangas, but after downloading the list from server the list is very small in fmd [only 1145 and the data size is 55 KB). I don't know if there's any problem with downloading from madokami because i haven't tried it. But could u fix madokami manga list problem.

**Comment by riderkick** [comment]
There is no working prebuild madokami list at the moment. Try to build from scratch. Or just drop the url(s) to download list or favorite list.
@TokcDK can you try to rebuild this mangalist. Delete the old one if any. It may appear no progress, but actually it is still working(as long there is a network activity). Thanks to the structure of madokami that use many subdirectory, I have to scan them manually from single function, so there is no immediate update to the ui.

**Comment by TokcDK** [comment]
Also cand rebuild any from madokami. If i donloaded db drom sourceforge and then use update db option then when it start it make temp file in the data then check 27/27 and 10/10 and delete temp file but db not updated with same size. Tried to read online any but https://manga.madokami.al requires autorisation for this or will be 401 error and i have no any password for the madokami. Maybe it cant updated because autorisation?

**Comment by riderkick** [comment]
Yes you can't access madokami without user/password. I don't remember how I can get one.

**Comment by Souravi785** [comment]
I am already a member and I signed in on fmd.And i tried deleting the data and updating the list but no improvement.
