### ISSUE TITLE
Mangafox not completing Download

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#652]
i got this message on log file, 
17:50:24:247 TTaskThread, checkforfinish failed=17/17 "One Piece" > "One Piece 870 Parting"

when i open the website it work normally.

**Comment by riderkick** [comment]
There is always this one page that can't be loaded. It's usually at the last page on the latest chapter.
If you open with your browser, you can see it's indeed can't be loaded. I don't know how to eliminate it, because the url look valid until the image file is loaded.
http://mangafox.me/manga/one_piece/vTBD/c871/22.html

**Comment by StormJumper** [comment]
Sounds like they are putting up a big wall from being downloaded. If that is the case then MangaFox is getting strict.
