### ISSUE TITLE
duplicates present in the manga list

### ISSUE THREAD

**Issue by anshbansal** [riderkick/FMD#68]
The manga list being shown contains duplicates for every manga. 

I checked the options >> Updates and saw the option "Remove duplicate ....". That was already checked but the manga list was duplicate.

**Comment by anshbansal** [comment]
It may be that I am using the incorrect option. What is the difference between Download and update manga list?

**Comment by riderkick** [comment]
I grab the old mangalist from original project in sourceforge. Old fmd using title for primary key, that's why there is duplicate data. In recent unofficial fmd, I change it to url, and there's option to remove duplicate from local data when doing update list, this procedure may take long time for large list, because we will need to compare all the item with each other. Options>Updates>Remove duplicate data.

- Download list from server: download prebuild mangalist from server, Usefull for first use of website, because building data directly from scratch will take some time.
- Update mangalist: build/update mangalist directly from corresponding website. Download from server first so it just grab the new title that's not exist on local data. You can build from scratch to get valid data, but it will take some time.

At some point there is possibility there is a title which doesn't exist anymore on website, you have to build from scratch to get valid data.
But most of the it doesn't matter, because fmd not intended to browse the catalog, it's downloader. Furthermore it's impossible to get valid data without integration with the website.
