### ISSUE TITLE
Download problem is NOT a download problem

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#689]
The issue that is happening is not that the downloads do not complete but that for some reason it does not archive all the folders.  For example download all volumes of The Gamer on Kissmanga.  Chapter 24 all downloaded completely but would not archive so it just remain stuck and failed even if you try to resume.

**Comment by riderkick** [comment]
The recent commit contains some fixes for path issue, you can try that. Maybe it's already fixed.

**Comment by riderkick** [comment]
[fmd.7z.txt](https://github.com/riderkick/FMD/files/1185831/fmd.7z.txt)

**Comment by matoro** [comment]
I am getting this issue as well, if I'm interpreting it correctly - I have things set to compress to pdf.  Around 10% of chapters or so will silently fail to compress.  About 20% of those chapters will leave a chapter folder with image in it.  However they will be missing about 1-2 images per chapter, random as far as I can tell.  The remaining 90% of of failures will leave an empty chapter folder behind, but no pdf.  The failed chapters are random and not the same if I download the same series twice.  I can of course go in and redownload the failed chapters manually.

**Comment by riderkick** [comment]
Those are failed chapter(s), upon the end of task run. The task will show as failed task. Then, you can resume it later. On the future version there will be auto resume failed task with customized retry count.

There is indeed an issue which causing fmd to mark failed chapter with as finished. fixed in https://github.com/riderkick/FMD/commit/0d019cce47c7c3034d496ac15b2dd19dd8782fa9

https://github.com/riderkick/FMD/compare/0.9.124.0...master

**Comment by molitar** [comment]
I just tested this and I went through all the chapters and downloads are completed all pages are there but I have just downloaded Brawling Go chapters 74-94 and so I have 20 folders that did not archive. I go into each folder and browse pages and they are complete.  It reports problem downloading even after resuming but its' completed.. Downloading from the site EatManga.

**Comment by riderkick** [comment]
Not compressed chapter should showed up as failed at the end of taks run. https://github.com/riderkick/FMD/blob/791d1e3c0536a44d649dca3be623cb04cfa45d71/baseunits/uDownloadsManager.pas#L1287-L1288

**Comment by molitar** [comment]
If that is the case is there anyway we can have it archive it anyway?  If eatmanga is going to show downloads incomplete all the time it's going to be hard to download from there.

**Comment by riderkick** [comment]
Forcing failed chapter to compress is not the right thing. Sometime it is just a temporary connection/server issue. You can compress them manually if you insist. cbz is just a zip.

**Comment by molitar** [comment]
But the thing is they are completed.  I ran them through Honeyview and every file is perfectly fine.

**Comment by riderkick** [comment]
If they are complete they will be compressed. Otherwise failed.
Before compress it will check for all pages, if all files exist then proceed. If not status failed.
It is status finished or failed?

There is also an issue causing failed chapter(s) always marked as finished. Which is fixed with commit https://github.com/riderkick/FMD/commit/0d019cce47c7c3034d496ac15b2dd19dd8782fa9.

Try to add the same chapter(s), it will look for the files and skip them if exist and only download what not exist, then continue to compress.

**Comment by molitar** [comment]
Yep new version fixed it.. I now have them archived and successful
