### ISSUE TITLE
[Site Request] Dynasty Scans

### ISSUE THREAD

**Issue by Nandaka** [riderkick/FMD#75]
Hi,

Can you add http://dynasty-scans.com/series?

**Comment by riderkick** [comment]
![sshot-1](https://cloud.githubusercontent.com/assets/4972676/8765027/422e06ac-2e2c-11e5-9749-03c03820f9cf.jpg)

**Comment by Nandaka** [comment]
Sorry for that, I'm using  0.9.7.1 and I cannot find it on the list.

Anything else beside updating to the latest? The mediafire folder (https://www.mediafire.com/folder/3ccy2c7g36hp3/) doesn't list Dynasty-scan as the data

**Comment by riderkick** [comment]
Why don't you use the latest version (0.9.18.2). https://github.com/riderkick/FMD/releases
You've been miss a lot of updates.
Data have been moved to https://bintray.com/riderkick/FMD/data/all
You can download the data within fmd since 0.9.x, updates also working.

**Comment by Nandaka** [comment]
Ahahah, google search still point to the sourceforge and akarink.wordpress.com website, so I don't know about this changes :smile:

**Comment by riderkick** [comment]
There is must be some info on there.
Yes, people often confused with github, and ask where is the compiled file, even though the release tab is right on the top. 😓

I forgot to mention, because you come long way from previous version, it's recommended to use fresh copy of fmd, you can try to copy your works.ini and favorites.ini later, but it's recommended to rebuild from scratch to avoid some issue that may present due to structure changes in downloadmanager/favoritesmanager.
