### ISSUE TITLE
Download favorites 

### ISSUE THREAD

**Issue by Alter00** [riderkick/FMD#85]
Hello,
FMD does not download when checking favorite is completed. Just searching and finished, nothing happined. I hope you will fix this.
Thank you in advance.

**Comment by GatesDA** [comment]
Which websites are you checking?  Since the rewrite I've found Batoto fails with high concurrent connections.  I had 8 tasks / 16 files / 15-second timeout and wasn't getting any Batoto updates with the bulk checker.  It worked if I checked individually, but then I got download errors.

Dropping both to 2 with a 30-second timeout fixed it, but I'll be experimenting with how high I can raise these limits.

**Comment by Alter00** [comment]
I check many site like kissmanga, batoto, mangastream. However new mangas come from bato.to so it should download mangas from bato.to.

**Comment by GatesDA** [comment]
Does dropping the concurrent connections not fix it for you?

-----Original Message-----

**Comment by Alter00** [comment]
I cannot say I understand how should i drop concurrent connections.

**Comment by riderkick** [comment]
It seems ba to to has concurrent connection limit. The server will reply with `503 Service unavailable` if we have more than 4 connection. The limit is applied to ip address.
