### ISSUE TITLE
[Site-support request] Sea Otter Scans

### ISSUE THREAD

**Issue by ksrock752** [riderkick/FMD#969]
English scanlation site

[https://reader.seaotterscans.com/](url)

**Comment by ralvarador** [comment]
That web page looks like being using the foolslide...
You can try this...
<FMD-FOLDER>\lua\modules
There, you should find a file named "FoOlSlide.lua"; open it with a text-editor (don't use NOTEPAD because it's using UNIX End-of-Line and notepad will show the text like one-line-text... wordpad, notepad++, MS-WinWord should works fine)...

in the file you will see (at the bottom) with format AddWebsiteModule('LABEL', 'URL')
Add a new one line with https://reader.seaotterscans.com: **AddWebsiteModule('Sea Otter Scans', 'https://reader.seaotterscans.com', cat)**

Save the file; - If FMD already was open, close it and then - reopen.

And try again. just with that changes was possible use the webpage (and because it use the 'https://reader.seaotterscans.com/directory/' for the Series List URL)

![image](https://user-images.githubusercontent.com/30580377/36176657-57219318-10e1-11e8-8558-945014f325be.png)

![image](https://user-images.githubusercontent.com/30580377/36176676-66784ab4-10e1-11e8-84f3-33b636a6285e.png)
