### ISSUE TITLE
Feature Request Zip File compression level

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#999]
can you add zip compression level as an option ?
or make custom zip command line to acomodate it ??

**Comment by riderkick** [comment]
There is no point to set compression level for image files. ZIP/CBZ now saved with clNone (store only). Forcing to compress image files will not gonna shrink the size, on the contrary it may increase the size due to extra unused dictionary. That's why I change it to clNone. It used to be clDefault. Nothing to gain but loss in cpu and disk space.
